collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5430108
color:
  saturation: 0.8026316
  brandStrength: 0.6779448
  lightness: 0.5043859
  brandColors:
    - '#B5ABA3'
    - '#786E64'
    - '#E8E0DF'
    - '#FA7678'
    - '#C65C5C'
  rhythmicContrast: 0
layout_spectrum: 0.6798246
name: Watercolors by an Architect
