layout_spectrum: 1
color:
  saturation: 0.9750598
  brandStrength: 0.8028674
  lightness: 0.5913978
  brandColors:
    - '#020101'
    - '#D1D6BD'
    - '#89916E'
    - '#BD7802'
    - '#019142'
  rhythmicContrast: 0.4767025
typography_spectrum: 0.5430108
name: Watercolors by an Architect
