collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5430108
color:
  saturation: 1
  brandStrength: 0.6779448
  lightness: 0.5004664
  brandColors:
    - '#040305'
    - '#A1A2A5'
    - '#5C5E64'
    - '#CEA54A'
    - '#C71737'
  rhythmicContrast: 0.7825814
layout_spectrum: 0.7028918
name: Watercolors by an Architect
