collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5012531
  brandStrength: 0.8028674
  lightness: 0.5043859
  brandColors:
    - '#020101'
    - '#D1D6BD'
    - '#89916E'
    - '#BD7802'
    - '#019142'
  rhythmicContrast: 1
typography_spectrum: 0.5430108
layout_spectrum: 0.6798246
name: Watercolors by an Architect
